RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 300
CHUNK_OVERLAP: 30
DATA_PATH: 'data/'
DB_FAISS_PATH: 'vectorstore/db_faiss'
MODEL_TYPE: 'mistral'
MODEL_BIN_PATH: 'models/mistral-7b-instruct-v0.2.Q4_K_S.gguf'
EMBEDDINGS: 'finiteautomata/bertweet-base-sentiment-analysis'
MAX_NEW_TOKENS: 1048
TEMPERATURE: 0.01